version: "3"

services:
  # backend:
  #   build:
  #     context: backend
  #     target: builder
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      # - MYSQL_RANDOM_ROOT_PASSWORD=false
    ports:
      - 3306:3306
      - 33060:33060
  # proxy:
  #   image: nginx
  #   volumes:
  #     - type: bind
  #       source: ./proxy/nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #       read_only: true
  #   ports:
  #   - 80:80
